// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhc19YfQeFFt6U_iCVHxp89Jg46RCXBiI',
    appId: '1:60217533357:web:6b8cd1bc7ec3ae5d307724',
    messagingSenderId: '60217533357',
    projectId: 'doctorappointmentapp-d110c',
    authDomain: 'doctorappointmentapp-d110c.firebaseapp.com',
    storageBucket: 'doctorappointmentapp-d110c.firebasestorage.app',
    measurementId: 'G-BC37ST3HCH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDme9u6p0a8E2PCB_PeuNOLUtmeij3RAFA',
    appId: '1:60217533357:android:2603491263e24f70307724',
    messagingSenderId: '60217533357',
    projectId: 'doctorappointmentapp-d110c',
    storageBucket: 'doctorappointmentapp-d110c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBWS6cL3Ux0Y-n1vN0U4fiQwu82xqeRL0',
    appId: '1:60217533357:ios:c0983d3ceb4ebe47307724',
    messagingSenderId: '60217533357',
    projectId: 'doctorappointmentapp-d110c',
    storageBucket: 'doctorappointmentapp-d110c.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointmentApi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBWS6cL3Ux0Y-n1vN0U4fiQwu82xqeRL0',
    appId: '1:60217533357:ios:c0983d3ceb4ebe47307724',
    messagingSenderId: '60217533357',
    projectId: 'doctorappointmentapp-d110c',
    storageBucket: 'doctorappointmentapp-d110c.firebasestorage.app',
    iosBundleId: 'com.example.doctorAppointmentApi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhc19YfQeFFt6U_iCVHxp89Jg46RCXBiI',
    appId: '1:60217533357:web:81ecff95083af26a307724',
    messagingSenderId: '60217533357',
    projectId: 'doctorappointmentapp-d110c',
    authDomain: 'doctorappointmentapp-d110c.firebaseapp.com',
    storageBucket: 'doctorappointmentapp-d110c.firebasestorage.app',
    measurementId: 'G-9VNWV8RLWQ',
  );
}
